### PR TITLE
Initial support for signed charts

### PR DESCRIPTION
**Pull request by tonsV2**
In order to address [this](https://github.com/hypnoglow/helm-s3/issues/150) issue I've opened this pull request. Please let me know if there's anything you'd like me to do differently.

I'd also greatly appreciate some thoughts on how to properly implement tests.

### CODE REVIEW

**Comment by Yunir** [comment]
Hi, @hypnoglow! 
May you clarify what is the stopper for this issue to be merged? 
What should be done for it?

**Comment by vineetguptadev** [comment]
what is the content type for `provenance` file in this .

**Comment by vineetguptadev** [comment]
@tonsV2 Thanks for PR , do we know when should we expect the PR to land , I think support for provenance file `must` be there in Chart Museum  API Spec compliant registry https://github.com/helm/chartmuseum.

**Comment by tonsV2** [comment]
@vineetguptadev You'll have to ask @hypnoglow about that. I moved on, I'm not even using this util anymore.

**Pull request closed without merging**
